### ISSUE TITLE
[BUG] <Mixed keys>

### ISSUE THREAD

**Issue by Mathias-Boulay** [Mathias-Boulay/PojavLauncher#5]
Thanks to @LegacyGamerHD
*Updated with added information from comments*

### Describe the bug
Moving the mouse around will trigger key events

**Add a log file if you want to see your bug fixed !**
[latestlog .txt](https://github.com/Mathias-Boulay/PojavLauncher/files/6810382/latestlog.2.txt)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Launch any Minecraft version with a keyboard/mouse combo plugged in
3. Moving the mouse will trigger keyboard events if the keyboard was used beforehand.

### Expected behavior:
I expected the mouse not to trigger such events

### Screenshots or videos:
🤷 

**Platform:**
 - Device Model sm-t500
 - CPU architecture aarch64
 - Android Version 11 
 - PojavLauncher Version ""latest from virtual controller revamp""

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
https://www.amazon.nl/Trust-Tecla-2-Draadloos-Toetsenbord-Zwart/dp/B07YMJM2XQ/ref=asc_df_B07YMJM2XQ/?tag=nlshogostdsp-21&linkCode=df0&hvadid=430515393747&hvpos=&hvnetw=g&hvrand=1976038857501305885&hvpone=&hvptwo=&hvqmt=&hvdev=m&hvdvcmdl=&hvlocint=&hvlocphy=9064152&hvtargid=pla-898234157645&psc=1
</pre>
</details>

**Comment by WesleyVanNeck** [comment]
device model: sm-t500

**Comment by WesleyVanNeck** [comment]
android version 11

**Comment by LegacyGamerHD** [comment]
crash with apk send this was the named false 
[crash-2021-01-16_12.33.59-client.txt](https://github.com/Mathias-Boulay/PojavLauncher/files/6811109/crash-2021-01-16_12.33.59-client.txt)
